name: ci

on: [ push, pull_request]

jobs:
  clone-and-install:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install bootstrap dependences on MacOS
        run: |
          set -x
          brew install curl
        if: startsWith(matrix.os, 'macos')
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install Chezmoi and apply dotfiles
        run: |
          set -x
          ./install.sh
      - name: Test dotfiles are installed properly
        run: |
          '"$HOME/.local/bin/chezmoi" data'
