name: ci

on: [ push, pull_request]

jobs:
  clone-and-install:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Remove all crap from MacOS
        run: >-
          set -x;
          brew remove --cask --force $(brew list);
          brew remove --force $(brew list --formula);
          brew install curl
        if: startsWith(matrix.os, 'macos')
      - uses: actions/checkout@v3
        with: { fetch-depth: 1}
      - name: Install ZSH on Linux
        run: >-
          sudo apt-get update;
          sudo apt-get install zsh
        if: runner.os == 'Linux'
      - name: Install Chezmoi and apply dotfiles
        run: >-
          set -x;
          ./install.sh
      - name: Test BASH environment sanity
        run: >-
          set -x;
          chezmoi data
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash -e {0}
      - name: Test ZSH environment sanity
        run: >-
          set -x;
          env;
          chezmoi data
        shell: zsh -il -e {0}
        if: startsWith(matrix.os, 'macos')
